### ISSUE TITLE
[v0.0.8] Error with low values in ETH pool

### ISSUE THREAD

**Issue by GrassRootsCrypto** [thorchain/asgardex-electron#1233] opened 2021-03-30 05:53 UTC
Likley the same issue as #1215
## Prerequisites

- [ ] Using yarn dev
- [ ] Using node 12.x
- [ ] Using an up-to-date [master branch](https://github.com/thorchain/asgardex-electron/tree/master/)
- [ ] Link to stacktrace in a Gist (for bugs)

## Expected Behavior

Adding to an ETH pool

## Current Behavior

![image](https://user-images.githubusercontent.com/40199525/112939797-3f08c680-916b-11eb-897b-5c8c5048d6d1.png)
So I believe the values trying to be entered were too low - this more than the gas.
![image](https://user-images.githubusercontent.com/40199525/112939867-6069b280-916b-11eb-8bce-a3301b14a08f.png)

Error Text is this:
"YOU DON'T HAVE SHARES IN THIS POOL
DEPOSIT ERROR
CANNOT ESTIMATE GAS; TRANSACTION MAY FAIL OR MAY REQUIRE MANUAL GAS LIMIT (ERROR={"REASON":"CANNOT ESTIMATE GAS; TRANSACTION MAY FAIL OR MAY REQUIRE MANUAL GAS LIMIT","CODE":"UNPREDICTABLE_GAS_LIMIT","METHOD":"ESTIMATEGAS","TRANSACTION":{"FROM":"0X3FDB073070FD7D3E1EA3A31BC8FD53353A872811","GASPRICE":{"TYPE":"BIGNUMBER","HEX":"0X178411B200"},"TO":"0X9D496DE78837F5A2BA64CB40E62C19FBCB67F55A","VALUE":{"TYPE":"BIGNUMBER","HEX":"0X0999895A99E400"},"DATA":"0X1FECE7B40000000000000000000000009B06A10BB5B90E1EC6982B1A876A13885446E86800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000384144443A4554482E4554483A7474686F72316C79356B68716771736B68336E666D76373566357A6D727632376168707937616C616A3979330000000000000000"}}, TX={"DATA":"0X1FECE7B40000000000000000000000009B06A10BB5B90E1EC6982B1A876A13885446E86800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000384144443A4554482E4554483A7474686F72316C79356B68716771736B68336E666D76373566357A6D727632376168707937616C616A3979330000000000000000","TO":{},"GASPRICE":{"TYPE":"BIGNUMBER","HEX":"0X178411B200"},"FROM":"0X3FDB073070FD7D3E1EA3A31BC8FD53353A872811","VALUE":{"TYPE":"BIGNUMBER","HEX":"0X0999895A99E400"},"NONCE":{},"GASLIMIT":{},"CHAINID":{}}, CODE=UNPREDICTABLE_GAS_LIMIT, VERSION=ABSTRACT-SIGNER/5.0.10)
"

## Possible Solution
Show a better error message than this please. Like a warning or something like that. 

## Steps to Reproduce (for bugs)
Load Assgard Ex.
Have about 0.006 ETH and try and add it to the ETH pool. 

## Context
Good to have user friendly error messages

**Comment by sarawut11** [comment] 2021-04-06 08:33
I can't reproduce the issue.
I guess, the balance is low than the gas fee in the above example and in this case, it is the same issue with #1215 
Hence closing this issue.

**Closed by sarawut11** 2021-04-06 08:33 UTC
Labels: bug
