### ISSUE TITLE
BUG: Unexpected double credit of ETH after BTC/ETH swap

### ISSUE THREAD

**Issue by jrh** [thorchain/asgardex-electron#1382] opened 2021-04-27 15:46 UTC
Posting this for a friend who isn't on Github:

Asgardex Desktop version 0.1.0
Windows 10 Home

Last night my friend made a BTC to ETH swap, and everything worked as expected.  Then when he checked his Asgardex app this morning the ETH appeared to have been triple credited on the interface history tab, and double credited when examining the ETH address on etherscan.

Thorchain transaction id:
https://thorchain.net/#/txs/D16F7C13BCDE7913B8F1A7BC788CFFB7BF2933F406A2D646891CFBDAF30E12EF

ETH wallet address:
0xf9898A14ffA7f183E76814A388d1eC6faa06da84

A second ETH transaction for duplicate amount appears to have been credited in the middle of the night.  Any explanation for this behavior?  Did this have something to do with cap raise?

**Comment by kaiansaari** [comment] 2021-04-27 22:01
Thanks for reporting this. The issue is with the protocol and not the wallet, so will be closing this issue.

DM me on telegram to discuss more: @kkkilo - thanks!

**Closed by kaiansaari** 2021-04-27 22:01 UTC
