### ISSUE TITLE
Swap $rune to $btc produces invalid address in Wallet > Assets

### ISSUE THREAD

**Issue by ngufyi** [thorchain/asgardex-electron#947] opened 2021-02-19 09:51 UTC
## Prerequisites

- [ ] Using yarn
- [ ] Using node 12.x
- [ ] Using an up-to-date [master branch](https://github.com/thorchain/asgardex-electron/tree/master/)
- [ ] Link to stacktrace in a Gist (for bugs)

## Expected Behavior

Swap $rune to $btc without error. 

## Current Behavior

I swapped $rune to $btc.  The transaction finished without error.  I then navigated to Wallet > Assets and see an invalid address for the Bitcoin I swapped to.  Biitcoin Addrress in UI is  tb1qgckhf0rlszdmguxv7z99d97nwxtcxhnvy4t9mf

Image of error in link
https://www.dropbox.com/s/ymxlk4dn822pvas/Screen%20Shot%202021-02-19%20at%203.36.19%20AM.png?dl=0

Link to 1st rune transaction
https://testnet.thorchain.net/txs/1FDA63C446AF1CF819FED785B3CEC125F2E5A38FDB3A7ACAF71166CA14AA9667

I tried to swap from $rune to $btc a second time (after receiving the invalid address error) for a smaller amount as seen in the transaction log
https://www.dropbox.com/s/ly7s52dvoynpmnr/Screen%20Shot%202021-02-19%20at%203.44.07%20AM.png?dl=0
This second transaction does not appear in the wallet but it does appear in the rune transaction list

Link to 2nd rune transaction
https://testnet.thorchain.net/txs/8195C064B177A3AF854978B5BE4023F9A6FFDC19508254399F21061BE3255EF9

Now when I go to Pools > BTC > Manage I get a message = NEEDED FEE OF ⚡ 1,560 IS NOT COVERED BY YOUR BALANCE: ⚡ 0 
https://www.dropbox.com/s/kaqi39y2et7d055/Screen%20Shot%202021-02-19%20at%203.49.09%20AM.png?dl=0

But when I go to Pools > BNB > Manage I don't get that message
https://www.dropbox.com/s/s7ywong7ouod5ww/Screen%20Shot%202021-02-19%20at%203.50.25%20AM.png?dl=0

## Possible Solution

Swap $rune to $btc without error.

## Steps to Reproduce (for bugs)

1. swap rune to btc
2. navigate to wallet then assets
3. invalid address error appears https://www.dropbox.com/s/ymxlk4dn822pvas/Screen%20Shot%202021-02-19%20at%203.36.19%20AM.png?dl=0

## Context
NA

## Your Environment

- Node version :
- Version or Branch used : v0.0.5
- Operating System and version : Mac v11.0.1
- Link to your project :

**Comment by junkai121** [comment] 2021-03-19 11:46
We are closing this issue since we couldn't reproduce the steps now.

We have tested with multiple accounts like: 
- an account with both RUNE/BTC balances.
- a new account with only RUNE balances and no BTC.

**Closed by junkai121** 2021-03-19 11:46 UTC
Labels: bug
