### ISSUE TITLE
The new "Total" displayed at the top of the Wallet section is incorrect. 

### ISSUE THREAD

**Issue by nightowl77** [thorchain/asgardex-electron#2200] opened 2022-04-05 14:48 UTC
When you open the wallet and manually add the totals of all the chain-wallets together (ie ETH, BTC and Terra totals), the amount you get is not the same as the total displayed at the top. 

## Current Behavior

The totals are inflated and not correct. 

## Steps to Reproduce

1. Start Asgard 0.12.3
2. Add any 3 coins to the wallet
3. Manually add the USD totals of those 3 coins. 
4. The result is that the total is not the same as the automatically calculated Total at the top of the wallet. 

## Possible Solution

No idea (i'm going off the required template here in the "Issue submit form")

## Your Environment - Release Version (skip if not using a release version)

- ASGARDEX desktop version: 0.12.3

- Operating system and version: Tested on both Mac and Windows, but give the same result and same bug

- Node version: No idea, just installed AsgardDEX

- Yarn version: N/A

- Branch: N/A

- Operating system and version: Tried on both Windows and Mac

**Comment by veado** [comment] 2022-04-11 06:26
Amount of total balances are including values of 'pools' assets only. That's because there is no price oracle and only THORChain pool assets are used to compute total balances (either in USD, BTC, ETH or RUNE). Any asset, which is not part of any THORChain pool, can't be priced and not included in total amounts. 

Possible fix:
- Change title `total amount` to `total amount of pool assets` (incl. an `info` icon to display extra information what it means
- Remove `total balances` from `assets` view

**Comment by veado** [comment] 2022-04-11 12:56
[UPDATE]
- Bug confirmed - balances of BTC are included twice in total balances - it will be fixed shortly

**Closed** 2022-04-12 10:38 UTC
Labels: bug

**Comment by nightowl77** [comment] 2022-04-20 17:44
I've tried the latest version and the totals are 100% correct. Thank you very much!
