### ISSUE TITLE
unexpected issue when scroll swap slider in mobile view

### ISSUE THREAD

**Issue by ssdbkey** [thorchain/asgardex-electron#1195] opened 2021-03-25 15:30 UTC
![image](https://user-images.githubusercontent.com/35497333/112498981-9e588680-8db9-11eb-93f0-a5f9d0829e4c.png)

**Comment by chaindbkey** [comment] 2021-04-09 09:54
After research about the issue, I noticed that the issue is available on antd slider.
Found similar open issue in Antd Github.
https://github.com/ant-design/ant-design/issues/28787

**Comment by veado** [comment] 2022-08-23 09:15
Can't reproduce it anymore. Seems to be fixed in latest `antd`. _Closing for now_

**Closed by veado** 2022-08-23 09:15 UTC
Labels: bug
